[workspace]
resolver = "2"
members = [
  "btp",
  "codec",
  "common",
  "keyos",
  "router",
  "api",
  "fsm",
  "rpc",
  "runtime",
  "wire",
]

[workspace.package]
homepage = "https://github.com/Foundation-Devices/quantum-link"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bytes = "1.11.1"

# workspace crates
ql-codec = { path = "codec" }
ql-common = { path = "common" }
ql-fsm = { path = "fsm" }
ql-keyos = { path = "keyos" }
ql-rpc = { path = "rpc" }
ql-wire = { path = "wire" }
