[workspace]
resolver = "2"
members = [
  "ql-btp",
  "ql-codec",
  "ql-common",
  "ql-keyos",
  "ql-router",
  "ql-api",
  "ql-fsm",
  "ql-rpc",
  "ql-runtime",
  "ql-wire",
]

[workspace.package]
homepage = "https://github.com/Foundation-Devices/quantum-link"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bytes = "1"

# workspace crates
ql-codec = { path = "ql-codec" }
ql-common = { path = "ql-common" }
ql-fsm = { path = "ql-fsm" }
ql-keyos = { path = "ql-keyos" }
ql-rpc = { path = "ql-rpc" }
ql-wire = { path = "ql-wire" }
